### ISSUE TITLE
Feature Request: Find and Replace links (as per FS)

### ISSUE THREAD

**Issue by TorricRodas** [GenesisViewer/Genesis#183]
We knew this would be coming up as a request one day.   I don't know how easy or hard this is to do... I do know that it means messing around with people's inventory!!

daydreamer0581 Resident
(Genesis Release 706): Heylo. I am coming from Firestorm. Is there a "Find Links" and "Replace Links" equivalent in Genesis?
(Genesis Release 706): As if Genesis doesn't have it * yet * it's a very cool and necessary feature. In Firestorm I can right click on an object / wearable and pick "Replace Links" , it'll pop up a dialog box with the item / wearable at the top, drag & drop a new item / wearable onto the dialog box, and click "Replace", it'll find all symlinks (what Outfits use) for the old object / wearable and replace them with new symlinks for the new object / wearable. So if you wear a collar in all Outfits, have a few dozen Outfits, and that collar updates, or you decide to change collars, your not swapping to each and every single Outfit to update them, it does it all for you.

**Comment by MelyCosti** [comment]
closed by error

**Comment by TorricRodas** [comment]
No errors reported.. good to go on this
