### ISSUE TITLE
Feature Request: Turn speed for WASD

### ISSUE THREAD

**Issue by TorricRodas** [GenesisViewer/Genesis#239]
[Only if this doesn't degrade performance and is as simple as the user believes it to be]

When using arrow keys or WASD to turn the avatar left or right, it would be nice if the speed at which we turn could be adjusted.

I believe this is a one-line fix in moveview.cpp or whatever. It's been almost a decade since I touched the viewer's source code, please forgive me if that's not the right spot to look.

By default it takes a really long time to spin in a circle if you hold the left or right keys. Being able to adjust this value would be lovely - it's a QoL feature that you don't realize the importance of until you have it lol

Thank you love you etc
KissMy Foxpaws

**Comment by MelyCosti** [comment]
will have a look
