### ISSUE TITLE
Explore possibility of supporting multiple walks/jumps in built in AO

### ISSUE THREAD

**Issue by TorricRodas** [GenesisViewer/Genesis#24]
Destiny Wescott
BOT
 — Today at 18:21
(Genesis Release 522): Awesome... my lost and found was starting to overflow... I can finally clear it out one last time :)
(Genesis Release 522): Earlier this year, prior to the release of Gensis... One of the Singularity scripters assured me that the built in ao would allow for multiple jumps.  It seems this request didn't make it to Genesis.  Who do I need to butter up this time?

**Comment by MelyCosti** [comment]
obsolete
