### ISSUE TITLE
When a prompt dialog is shown, if it contains many lines, the last lines disappear behind the textbox

### ISSUE THREAD

**Issue by MelyCosti** [GenesisViewer/Genesis#286]
![image](https://github.com/GenesisViewer/Genesis/assets/105198589/e2a16188-06bc-44ea-97eb-87003cf2d601)

**Comment by TorricRodas** [comment]
this user on 830 says the problem persists..
![Snap0004](https://github.com/GenesisViewer/Genesis/assets/107435635/2295a6fa-2006-4674-af6b-9bb2053accac)
