### ISSUE TITLE
Bug??  Genesis limits length of password to 12 chars?

### ISSUE THREAD

**Issue by TorricRodas** [GenesisViewer/Genesis#290]
Hi, please can we check this and close the ticket if this is a red herring?  

Anne Addams
(Genesis Release 799): I cannot login when my pw is 16 chars long, so I had to shorten my pw to 12 chars to be able to login. Is that a known bug?

candicek15 Resident
(Genesis Test 824): not heard of that before anne no ..

Anne Addams
(Genesis Release 799): well I've tried it. my old pw was that long :)
(Genesis Release 799): ok. well it happened to me

Roni Nightingale
(Genesis Test 824): did you try logging in any other viewer before changing your password?

Anne Addams
(Genesis Release 799): Yes I did. Other viewers worked fine with my long pw

**Comment by MelyCosti** [comment]
@TorricRodas I changed my password to make it 16 characters long, and it works
