### ISSUE TITLE
Bad autobuild.xml

### ISSUE THREAD

**Issue by DigitallyFidget** [GenesisViewer/Genesis#442]
FMOD Package reference does not exist.
http://pkg.genesisviewer.org/fmodstudio-2.02.09-windows64-11102022.tar.bz2

**Comment by FidgetNebula** [comment]
Alchemy Viewer has a guide on building the FMOD package, if they don't update that, you can always build your own.

**Comment by MelyCosti** [comment]
autobuild works fine, fmod lib is not shareable

**Comment by MelyCosti** [comment]
you can use openal that is open source
