### ISSUE TITLE
Declined friendship offer from muted avatar should not send you a message

### ISSUE THREAD

**Issue by TorricRodas** [GenesisViewer/Genesis#66]
Currently says...
[02:57 AM]  Declined friendship offer from [NAME_SLURL]. [MESSAGE]

and should say nothing at all.  The avatar is muted, you don't want to hear anything from those you blocked.

**Comment by MelyCosti** [comment]
@TorricRodas can you explain me how to reproduce this?

**Comment by TorricRodas** [comment]
If you mute an Alt account from your main,  then get the Alt to send you a friendship request, you will get the message above in local chat.

I believe that autoresponse to muted should still show in local as they already do, so that you know they are trying to contact you (and you only see that the auto response has been sent once),  but if they spam you with friendship requests, you will see the declined message each time they send a request.
