### ISSUE TITLE
WASD movement made simpler

### ISSUE THREAD

**Issue by TorricRodas** [GenesisViewer/Genesis#71]
Move WASD from Preferences > text chat
And REVERSE the logic on the corresponding debug for this:     'Letter keys start typing in local chat' (default is true)

Move to Prefs > input and camera in the "movement section"

Relabel the option as "WASD to control movement?"  and have it unchecked by default (default is false)
Add a tooltip saying: "When unchecked, the keyboard arrow keys move your avatar"

**Comment by Shep1962** [comment]
the LetterKeysFocusChatBar debug settings , should have it's description changed to 
'LetterKeysFocusChatBar: When printable characters keys (possibly with Shift held) are pressed, the chatbar takes focus.   Set to false for WASD operation'

**Comment by Shep1962** [comment]
[Genesis Viewer proposal of changes to WASD options.docx](https://github.com/GenesisViewer/Genesis/files/10335612/Genesis.Viewer.proposal.of.changes.to.WASD.options.docx)

**Comment by Shep1962** [comment]
[Genesis Viewer proposal of changes to WASD options 1.docx](https://github.com/GenesisViewer/Genesis/files/10339541/Genesis.Viewer.proposal.of.changes.to.WASD.options.1.docx)
