### ISSUE TITLE
Ability to IM yourself .. handy for notes and pasting slurls

### ISSUE THREAD

**Issue by TorricRodas** [GenesisViewer/Genesis#98]
When I kick someone out of a group I get an IM from myself to myself..  If we can make it so you can IM yourself for notes, I think that would solve the issue of people asking where to paste slurls... and good for note keeping.
- Torric

**Comment by MelyCosti** [comment]
IM Myself option added to Communicate button in the toolbar
![image](https://user-images.githubusercontent.com/105198589/213866291-00f74c41-d60b-4551-85f8-0ad2c5d962ad.png)
